In [1]:
import numpy as np

In [44]:
array=np.array([3,2,4,5,2])

In [45]:
type(array)

numpy.ndarray

#### Array Operations ####

In [46]:
n1=np.array([3,5,2,1])
n2=np.array([2,5,6,7])


In [47]:
n1*n2

array([ 6, 25, 12,  7])

In [48]:
n1+n2

array([ 5, 10,  8,  8])

In [49]:
np.sqrt(n1)

array([1.73205081, 2.23606798, 1.41421356, 1.        ])

#### indexing and slicing (Accessing Elements of array) ####

In [66]:
##1d array (nd array)
a1=np.array([1,3,5,6,9])
#indexing
print(a1[4])
#Slicing
print(a1[1:4])

9
[3 5 6]


### Boolen Indexing ###


In [51]:
a1[a1>3]

array([5, 6, 9])

##### Reshaping of Array #####

In [ ]:

rarray=np.arange(10)
rarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
len(rarray)

10

In [54]:
rarray.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
rarray.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
array=rarray.reshape(2,5)

In [57]:
array[1][3]

np.int64(8)

In [58]:
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
array[1:4,0:2]

array([[5, 6]])

In [60]:
array=rarray.reshape(5,2)

In [61]:
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
array[1:3,1:2]

array([[3],
       [5]])

#### Matrix Multiplication ####

In [63]:
m1 = np.ones((3,2))
m2 = np.array([[3,4,5],[5,2,1]])
print(m1.shape)
print(m2.shape)
              

(3, 2)
(2, 3)


In [64]:
np.dot(m1,m2)

array([[8., 6., 6.],
       [8., 6., 6.],
       [8., 6., 6.]])